cargo-features = ["edition"]

[package]
name = "larkc"
version = "0.1.0"
authors = ["Jonathan Turner <jonathan.d.turner@gmail.com>", "Yehuda Katz <wycats@gmail.com>"]
edition = '2018'

[dependencies]
seahash = "3.0.5"
codespan = "0.1.3"
derive-new = "0.5.5"
smart-default = "0.2.0"
lalrpop-util = "0.16.0"
derive_more = "0.11.0"
lazy_static = "1.1.0"
log = "0.4.5"
unicode-xid = "0.1.0"