[package]
name = "larkc"
version = "0.1.0"
authors = [
    "Jonathan Turner <jonathan.d.turner@gmail.com>",
    "Yehuda Katz <wycats@gmail.com>",
    "Niko Matsakis <niko@alum.mit.edu>"
]
edition = '2018'

[dependencies]
codespan = "0.1.3"
derive-new = "0.5.5"
derive_more = "0.11.0"
lalrpop-util = "0.16.0"
lazy_static = "1.1.0"
log = "0.4.5"
rustc-hash = "1.0"
seahash = "3.0.5"
smart-default = "0.2.0"
typed-arena = "1.4"
unicode-xid = "0.1.0"
itertools = "0.7.8"

[dev-dependencies]
unindent = "0.1.3"
language-reporting = { git = "https://github.com/wycats/language-reporting.git" }
termcolor = "1.0.3"
pretty_env_logger = "0.2"
